export const burgers = [
  {
    id: '1',
    name: 'Extra Beef Burger',
    description: 'This is a Beef Burger!',
    rating: '7.8',
    mass: '200g',
    type: 'Beef',
    price: '82',
    ingredients: "Beef",
    category: 'Burgers',
    image: "/images/burger1.webp",
  },
  {
    id: '2',
    name: 'Cheese & Bacon',
    description: 'This is a Cheese & Bacon Burger!',
    rating: '6.5',
    mass: '150g',
    type: 'Beef & Bacon',
    price: '69.99',
    ingredients: "Cheese",
    category: 'Burgers',
    image: "/images/burger2.webp",
  },
  {
    id: '3',
    name: 'Veggie Burger',
    description: 'This is a Veggie Burger!',
    rating: '8',
    mass: '120g',
    type: 'Vegetarian',
    price: '59.99',
    ingredients: "Soy",
    category: 'Burgers',
    image: "/images/burger3.webp",
  },
  {
    id: '4',
    name: 'Double Cheese',
    description: 'This is a Double Cheese Burger!',
    rating: '7.7',
    mass: '180g',
    type: 'Cheese',
    price: '85.99',
    ingredients: "Cheese, Beef",
    category: 'Burgers',
    image: "/images/burger4.webp",
  },
]
export const categories = [
  {
    id: '1',
    name: 'Burgers',
    image: "/images/burger.jpg",
  },
  {
    id: '2',
    name: 'Wings',
    image: "/images/burger.jpg",
  },
]
